### ISSUE TITLE
Kubernetes trials and errors

### ISSUE THREAD

**Issue by thiDucTran** [franzinc/docker-agraph#10]
1. `entrypoint.sh`, there needs to be a note or have `chmod +x entrypoint.sh` in the `Dockerfile` ..to avoid the assumption that `entrypoint.sh` is executable
2.  `entrypoint.sh`, afaik and atm, the block of code below is INSIDE the `# No agraph.cfg set, run configure-agraph` logic flow....I am pretty sure this is not correct and needs correction..i believe the intended pseudo code is: if user config file found..do something ..else (no  user cfg file) do something....after all of that run the block of code below
```bash
/agraph/lib/configure-agraph \
        --non-interactive \
        --config-file $AG_CFG_FILE \
        --data-dir $AG_DATA_DIR \
        --log-dir $AG_DATA_DIR \
        --super-user "$AGRAPH_SUPER_USER" \
        --super-password "$AGRAPH_SUPER_PASSWORD" \
        --session-ports 10000-10034 \
        --runas-user $AG_RUNAS_USER
```
3. the equivalent of Docker's `shm` in k8s is as below. See https://franz.com/agraph/support/documentation/current/docker.html
```yaml
volumes:
- emptyDir:
    medium: Memory
    sizeLimit: 2Gi
  name: cache-volume

volumeMounts:
- mountPath: /dev/shm
  name: cache-volume
```
4. Finally, if you plan to use ConfigMap to mount `agraph.cfg` to your pod... don't do it ...mounted configmaps are read-only... so when `entrypoint.sh` runs (assuming that it is fixed as mentioned in point number 2) as instructed by the `Dockerfile`'s entrypoint...it will fail because running `/agraph/lib/configure-agraph` means changing `agraph.cfg` ..which is a mounted configmap volume......so read-only..the error you would get is like below.
```
Found user-defined AllegroGraph configuration at /agraph/etc/agraph.cfg
/agraph/lib/configure-agraph: line 574: /agraph/etc/agraph.cfg: Read-only file system
```

FYI, we thought we were slick by changing this in `entrypoint.sh` ..meaning ignore the file `agraph.cfg` ..but in the end ..it doesn't matter
```bash
# Find all files not owned by $AG_RUNAS_USER in the /agraph/data and
# /agraph/etc directories (volume mount points) and change ownership
# to $AG_RUNAS_USER:$AG_RUNAS_GROUP.

find /agraph/data /agraph/etc \! -user agraph \! -name '*.cfg' -exec sudo chown $AG_RUNAS_USER {} +
```

**Comment by OLDlayeratwork** [comment]
I'm trying to understand if you're providing feedback or are asking for help.  Can you clarify that?  Thanks.

**Comment by thiDucTran** [comment]
I am providing feedback but if there is any documentation, tips for running in k8s..such as https://allegrograph.com/multi-master-replication-clusters-in-kubernetes-and-docker-swarm/?print=print ..then please let us know.

**Comment by OLDlayeratwork** [comment]
The above seems to be based on [this](https://github.com/franzinc/agraph-examples/blob/master/clustering/kubernetes/mmr/kubernetes-mmr.md).  Have you seen that?
