### ISSUE TITLE
update 6.0.2

### ISSUE THREAD

**Issue by arademaker** [franzinc/docker-agraph#2]
I tried change the VERSION in makefile without success! How to upgrade to 6.0.2?

**Comment by OLDlayeratwork** [comment]
What happened when you did that?

**Comment by arademaker** [comment]
Well, now it worked! So I believe it is just a matter of update the VERSION string in the repo!

**Comment by OLDlayeratwork** [comment]
Good to hear.

**Comment by arademaker** [comment]
why close it before update the VERSION value?

**Comment by OLDlayeratwork** [comment]
Just pushed the commit to fix this.
