### ISSUE TITLE
server warnning

### ISSUE THREAD

**Issue by arademaker** [franzinc/docker-agraph#3]
The current 6.0.1 start with a warnning:

thp 

Systemwide Transparent Hugepage (THP) support is enabled. Transparent Hugepages are known to cause performance problems for large databases. Consider disabling THP by executing (as root): `echo never > /sys/kernel/mm/transparent_hugepage/enabled`. For more information, see: http://franz.com/agraph/support/documentation/current/performance-tuning.html#THP

**Comment by OLDlayeratwork** [comment]
You are correct, if it detects THP is enabled, it gives that warning.  I'm not sure what you're getting at... if you require support, please send email to support@franz.com.
