### ISSUE TITLE
[question][documentation] SPARQL Endpoint

### ISSUE THREAD

**Issue by kuzeko** [franzinc/docker-agraph#5]
I want to send SPARQL queries via  REST.

What is the URL of the endpoint once this is running?
Alternatively, what is the `curl` command to do that?

Assume I created the catalog called `my_db`
I am expecting something like

```
curl "http://localhost/catalogs/sparql?query=SELECT%20*%20WHERE%20%7B%3Fs%20%3Fp%20%3Fo%7D%20LIMIT%208"
```

**Comment by OLDlayeratwork** [comment]
Please contact support@franz.com if you haven't figured this out.  It really has nothing to do with this repo.  Thanks.

**Comment by kuzeko** [comment]
Sorry for the confusion.
I am using the docker to run the `agraph` container, and then answer to the question is the only missing thing from the documentation of the image that I need. 
Hence the issue.

**Comment by OLDlayeratwork** [comment]
> Sorry for the confusion.
> I am using the docker to run the `agraph` container, and then answer to the question is the only missing thing from the documentation of the image that I need.
> Hence the issue.

Please send email to support@franz.com for this.  Thanks.
